import json
import numpy as np
import pytest
from pathlib import Path
import sys
import subprocess

# Auto-generate latest test data using Octave when running tests
try:
    tests_dir = Path(__file__).parent
    print("Regenerating test data baselines via Octave...", file=sys.stderr)
    subprocess.run(["octave", "--no-gui", "--no-window-system", "--quiet", "generate_test_data.m"], 
                   cwd=tests_dir, check=True, capture_output=True)
    subprocess.run(["octave", "--no-gui", "--no-window-system", "--quiet", "generate_gen_ch_data.m"], 
                   cwd=tests_dir, check=True, capture_output=True)
except Exception as e:
    print(f"Warning: Could not regenerate Octave test data: {e}", file=sys.stderr)

# Add parent dir to path so we can import the translation
sys.path.append(str(Path(__file__).parent.parent))

try:
    from music_fb_alg import music_fb_alg
except ImportError:
    def music_fb_alg(*args, **kwargs):
        raise NotImplementedError("music_fb_alg not yet translated to Python.")

def load_matlab_test_data():
    test_file = Path(__file__).parent / 'test_data_multi.json'
    if not test_file.exists():
        return []
    with open(test_file, 'r') as f:
        cases = json.load(f)
        # Ensure we return a list of tuples for pytest.mark.parametrize
        return [(c['name'], c['inputs'], c['outputs']) for c in cases]

MATLAB_CASES = load_matlab_test_data()

@pytest.mark.parametrize("name,inputs,expected", MATLAB_CASES)
def test_music_fb_alg_matlab_validation(name, inputs, expected):
    """
    Validates the Python translation of music_fb_alg directly against 
    the mathematically identical outputs generated by the original MATLAB/Octave script.
    """
    # Convert inputs to appropriate numpy arrays
    M = inputs['M']
    nsig = inputs['nsig']
    Nptot = inputs['Nptot']
    dists = np.array(inputs['dists'])
    cal_dist = inputs['cal_dist']
    threshold = inputs['threshold']
    S = np.array(inputs['S_real']) + 1j * np.array(inputs['S_imag'])
    CFR_data = np.array(inputs['CFR_data_real']) + 1j * np.array(inputs['CFR_data_imag'])

    # Call translated function
    dist_MUSIC, spec_dB, peakwidth = music_fb_alg(
        M, nsig, Nptot, dists, cal_dist, threshold, CFR_data, S
    )

    # Compare outputs
    expected_dist = np.array(expected['dist_MUSIC']).flatten()
    expected_spec = np.array(expected['spec_dB']).flatten()
    
    expected_peakwidth = expected['peakwidth']
    
    # Octave now natively returns width via findpeaks_compat wrapper
    np.testing.assert_allclose(dist_MUSIC.flatten(), expected_dist, rtol=1e-5, atol=1e-8, err_msg=f"{name}: dist_MUSIC mismatch")
    np.testing.assert_allclose(spec_dB.flatten(), expected_spec, rtol=1e-5, atol=1e-8, err_msg=f"{name}: spec_dB mismatch")
    if np.isinf(peakwidth):
        assert expected_peakwidth is None or expected_peakwidth == 0 or np.isinf(expected_peakwidth) or expected_peakwidth == 'Inf'
    else:
        np.testing.assert_allclose(peakwidth, expected_peakwidth, rtol=1e-5, atol=1e-5, err_msg=f"{name}: peakwidth mismatch")


# -------------------------------------------------------------
# Python-native Edge Case Tests
# -------------------------------------------------------------

def test_music_python_flat_spectrum():
    """
    Tests the scenario where CFR_data is purely white noise, ensuring 
    the spectrum calculation doesn't crash or return NaNs.
    """
    M, nsig, Nptot = 5, 2, 10
    dists = np.linspace(0, 10, 100)
    S = np.exp(1j * np.random.rand(M, 100))
    # Pure white noise
    CFR_data = np.random.randn(Nptot, 1) + 1j * np.random.randn(Nptot, 1)
    
    dist_MUSIC, spec_dB, peakwidth = music_fb_alg(M, nsig, Nptot, dists, 0, -10, CFR_data, S)
    
    # Check shape correctness
    assert dist_MUSIC.shape[0] == nsig, "Output distances should pad/truncate to nsig"
    assert spec_dB.shape == (1, 100), "Spectrum should be shape (1, num_dists)"
    assert not np.any(np.isnan(spec_dB)), "Spectrum should not contain NaNs"


@pytest.mark.filterwarnings("ignore:some peaks have a width of 0")
def test_music_python_zero_signal():
    """
    Tests edge case where CFR data is exactly zero to ensure division-by-zero is handled.
    """
    M, nsig, Nptot = 5, 2, 10
    dists = np.linspace(0, 10, 100)
    S = np.exp(1j * np.random.rand(M, 100))
    CFR_data = np.zeros((Nptot, 1), dtype=complex)
    
    dist_MUSIC, spec_dB, peakwidth = music_fb_alg(M, nsig, Nptot, dists, 0, -10, CFR_data, S)
    assert not np.any(np.isnan(spec_dB)), "Division by zero should be avoided in spec denominator."


def test_music_python_multi_antenna_symmetry():
    """
    Tests multi-antenna processing symmetry. A matrix with duplicated identical antennas 
    should produce mathematically identical covariance matrices and thus the exact same 
    spectrum as a single antenna of that data.
    """
    M, nsig, Nptot = 5, 2, 10
    dists = np.linspace(0, 10, 100)
    S = np.exp(1j * np.random.rand(M, 100))
    
    single_ant = np.random.randn(Nptot, 1) + 1j * np.random.randn(Nptot, 1)
    # Duplicate antenna columns
    multi_ant = np.hstack([single_ant, single_ant, single_ant])
    
    dist1, spec1, width1 = music_fb_alg(M, nsig, Nptot, dists, 0, -10, single_ant, S)
    dist2, spec2, width2 = music_fb_alg(M, nsig, Nptot, dists, 0, -10, multi_ant, S)
    
    np.testing.assert_allclose(spec1, spec2, rtol=1e-5, atol=1e-8, err_msg="Multi-antenna symmetry failed")
    np.testing.assert_allclose(dist1, dist2, rtol=1e-5, atol=1e-8, err_msg="Distances differed between symmetrical arrays")

def test_music_python_end_to_end_ranging():
    """
    Tests the algorithm end-to-end using physically generated IQ samples for a known distance.
    This simulates a real BLE two-way ranging signal and verifies the algorithm returns the correct physical distance.
    """
    from tests.gen_ch import gen_ch
    
    # Physics parameters
    dist_LOS = 15.0 # 15 meters
    c = 3e8
    delta_f = 1e6
    n = np.arange(-37, 38)
    Nptot = len(n)
    
    # Generate channel data (high SNR to ensure exact peak match)
    SNR = 40 
    CFR_data_array = gen_ch(num_runs=1, SNR=SNR, dist_vec=[dist_LOS], att_vec=[1.0], 
                            n=n, delta_f=delta_f, c=c, rayleigh=False)
    CFR_data = CFR_data_array[:, 0]
    
    # MUSIC parameters
    M = 15 # Subarray size
    nsig = 5
    taus = np.arange(0, 50, 0.001) / c # search space up to 50m
    dists = taus * c
    
    # Recreate the exact steering vector mathematically
    # S has dimensions M x len(taus)
    S = np.exp(-1j * 2 * np.pi * delta_f * np.outer(n[:M], taus))
    
    # Run the MUSIC algorithm
    dist_MUSIC, spec_dB, peakwidth = music_fb_alg(
        M, nsig, Nptot, dists, 0, -13, CFR_data, S
    )
    
    # In a two-way channel simulation, the delay/distance computed is round-trip
    estimated_distance = dist_MUSIC[0] / 2.0
    
    # Verify the estimation matches the physics input!
    np.testing.assert_allclose(estimated_distance, dist_LOS, rtol=1e-2, atol=0.1, 
                               err_msg=f"End-to-End ranging failed. Expected {dist_LOS}m, got {estimated_distance}m")

def test_gen_ch_translation():
    """
    Compares IQ sample data generated by Python gen_ch.py against the exact output 
    from MATLAB gen_ch.m to ensure the translation is mathematically identical.
    """
    from tests.gen_ch import gen_ch
    
    test_file = Path(__file__).parent / 'gen_ch_data.json'
    if not test_file.exists():
        pytest.skip("gen_ch_data.json not found.")
        
    with open(test_file, 'r') as f:
        data = json.load(f)
        
    inputs = data['inputs']
    expected_real = np.array(data['CFR_data_array_real'])
    expected_imag = np.array(data['CFR_data_array_imag'])
    expected_cfr = expected_real + 1j * expected_imag
    
    # Run the Python implementation
    python_cfr = gen_ch(
        num_runs=inputs['num_runs'],
        SNR=inputs['SNR'],
        dist_vec=np.array(inputs['dist_vec']).flatten(),
        att_vec=np.array(inputs['att_vec']).flatten(),
        n=np.array(inputs['n']).flatten(),
        delta_f=inputs['delta_f'],
        c=inputs['c'],
        rayleigh=inputs['rayleigh']
    )
    
    # Assert equivalence. Since SNR=300, noise is near zero.
    # Tolerances are tight because it's deterministic physics calculation.
    np.testing.assert_allclose(python_cfr, expected_cfr, rtol=1e-5, atol=1e-8,
                               err_msg="Python gen_ch output differs from MATLAB gen_ch.m")

def test_music_python_end_to_end_rayleigh():
    """
    Tests the algorithm end-to-end using physically generated IQ samples under Rayleigh fading conditions.
    This validates that the Python implementation of both the generator and the MUSIC algorithm 
    correctly handles severe random complex attenuation without crashing and still finds the peak.
    """
    from tests.gen_ch import gen_ch
    
    dist_LOS = 12.5
    c = 3e8
    delta_f = 1e6
    n = np.arange(-37, 38)
    Nptot = len(n)
    
    # Generate channel data with Rayleigh fading enabled
    SNR = 40 
    CFR_data_array = gen_ch(num_runs=1, SNR=SNR, dist_vec=[dist_LOS], att_vec=[], 
                            n=n, delta_f=delta_f, c=c, rayleigh=True)
    CFR_data = CFR_data_array[:, 0]
    
    M = 15
    nsig = 5
    taus = np.arange(0, 50, 0.001) / c
    dists = taus * c
    S = np.exp(-1j * 2 * np.pi * delta_f * np.outer(n[:M], taus))
    
    dist_MUSIC, spec_dB, peakwidth = music_fb_alg(
        M, nsig, Nptot, dists, 0, -13, CFR_data, S
    )
    
    estimated_distance = dist_MUSIC[0] / 2.0
    
    # Verify the estimation matches the physics input under Rayleigh conditions
    # Tolerance is slightly looser because Rayleigh fading alters the spectrum significantly
    np.testing.assert_allclose(estimated_distance, dist_LOS, rtol=1e-2, atol=0.5, 
                               err_msg=f"Rayleigh fading end-to-End ranging failed. Expected {dist_LOS}m, got {estimated_distance}m")

